name: taxi_rides
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20200923.3
  - adal=1.2.6
  - adlfs=0.6.3
  - aiohttp=3.7.4
  - arrow-cpp=3.0.0
  - async-timeout=3.0.1
  - attrs=20.3.0
  - aws-c-cal=0.4.5
  - aws-c-common=0.5.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.9.1
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.151
  - azure-core=1.12.0
  - azure-datalake-store=0.0.51
  - azure-identity=1.5.0
  - azure-storage-blob=12.6.0
  - blinker=1.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.6
  - fsspec=0.8.7
  - gflags=2.2.2
  - glog=0.4.0
  - grpc-cpp=1.36.2
  - idna=2.10
  - isodate=0.6.0
  - krb5=1.17.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.75.0
  - liblapack=3.9.0
  - libprotobuf=3.15.6
  - libssh2=1.9.0
  - libthrift=0.14.1
  - libutf8proc=2.6.1
  - lz4-c=1.9.3
  - mkl=2020.4
  - msal=1.10.0
  - msal_extensions=0.3.0
  - msrest=0.6.21
  - msrestazure=0.6.4
  - multidict=5.1.0
  - numpy=1.20.1
  - oauthlib=3.0.1
  - openssl=1.1.1j
  - pandas=1.2.3
  - parquet-cpp=1.5.1
  - pip=21.0.1
  - portalocker=1.7.0
  - pyarrow=3.0.0
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - re2=2020.11.01
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - setuptools=49.6.0
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.34.0
  - tk=8.6.10
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.3
  - wheel=0.36.2
  - xz=5.2.5
  - yarl=1.6.3
  - zlib=1.2.11
  - zstd=1.4.9